""" removed expiry date

Revision ID: 7419fbe7b31c
Revises: 52d63082a9f6
Create Date: 2026-02-10 09:51:35.244526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7419fbe7b31c'
down_revision: Union[str, Sequence[str], None] = '52d63082a9f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_status_messages'))
        batch_op.drop_column('expires_at')
        batch_op.create_index(batch_op.f('ix_chat_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_last_activity_at'), ['last_activity_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_status'), ['status'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('SYSTEM', 'USER', 'ASSISTANT', name='messagerole'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_role'), ['role'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_role'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))
        batch_op.alter_column('role',
               existing_type=sa.Enum('SYSTEM', 'USER', 'ASSISTANT', name='messagerole'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_last_activity_at'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_created_at'))
        batch_op.add_column(sa.Column('expires_at', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_chat_sessions_user_status_messages', ['user_id', 'status', 'message_count'], unique=False)

    # ### end Alembic commands ###
